#: schema https://json.schemastore.org/cargo.json
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "memospot"
version = "1.0.1"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
description = { workspace = true }

[lib]
name = "memospot_lib"
crate-type = ["staticlib", "cdylib", "lib"]

[build-dependencies]
tauri-build = { features = ["config-toml"], version = "2.0" }

[target.'cfg(not(local_crates))'.dependencies]
config = { path = "../config" }
dialog = { path = "../dialog" }
homedir = { path = "../homedir" }
migration = { path = "../migration" }
portpicker = { path = "../portpicker" }
writable = { path = "../writable" }

[dependencies]
anyhow = { workspace = true }
async_zip = { version = "0.0.18", features = ["zstd", "tokio-fs"] }
chrono = { version = "0.4", default-features = false }
encoding_rs = "0.8"
home = { workspace = true }
json-patch = "4.1"
log = { workspace = true }
log4rs = { version = "1.3", features = ["background_rotation", "config_parsing", "gzip", "yaml_format"] }
os_pipe = "1"
path-clean = "1.0"
sea-orm = { workspace = true, default-features = false, features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros"] }
semver = "1"
serde = { workspace = true }
serde_json = { workspace = true }
shared_child = "1.0"
strum_macros = "0.27"
tokio = { workspace = true }
ts-rs = { workspace = true }
url = { version = "2", features = ["serde"] }

[target.'cfg(not(i18n_group))'.dependencies]
i18n-embed = { version = "0.16.0", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.10.0"
rust-embed = "8"

[target.'cfg(not(tauri_group))'.dependencies]
tauri = { version = "^2.1", features = ["config-toml"] }
tauri-plugin-fs = "^2"
tauri-plugin-http = { version = "^2", features = ["gzip"] }
tauri-plugin-opener = "^2"
tauri-plugin-process = "^2"
tauri-plugin-shell = "^2"
tauri-utils = "^2"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "^2"

[target.'cfg(windows)'.dependencies]
tempfile = { workspace = true }
winreg = "0.55"

[dev-dependencies]
tempfile = { workspace = true }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
devtools = ["tauri/devtools"]

[package.metadata.cargo-machete]
ignored = ["tauri-build"]
